dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh
notifications:
  slack:
    rooms:
      secure: aJHzGgWucJ0MWlh/3vrcrEk1R+q/gsIAZ//YRY09g6IJl2SId186NtWFxp42FSmZPN6ipJbrBbSyeJbUJulTcgiWVu1R0qWYKATUGsvHkQAz5Zc5Geh9dMyeBlKl8QjyfZwaRLl/jL3wBOuMJzYwEp2xxf8Ym1hNVdGUgV0orkxhsNcMwimcUTY6rmj1p+QG1w9AUvahnZes4mIkcFPMStPyMh2abKenqsu5wmVk6R8tLVqnWELzdoXWjnVi0ON4FFHrugHbI/hlBpBpUhieu8+ojThehMZzF+F4YITMbG9sKsCRgOISH+W3iUDpmRZUpExv1q+5TUCoiJgzEtqKgosGtS7udufAksnKfYiG4ZvK2x78J85Q5jdjEtMMwQK2wysEODqonlGV7zSlOYSZmUrxvvQ9wirCK+k5YnNR7NzHMIIrmLJvXnGVrkrRPFuqvI22d/FFREY4EIGP9qSTpevjpFqO77I0gtsyRWUGHlbTn1M7iQDKOvRsH8KPRFibFNIEU0iPU72O36kfsoB4QAaWdVzGKOOELbk4nFMJUIqPgVRHP+Vir9O2ElPgQgNHPwcJHcNrfa0CIqI9zh53y6ccG0XEoNi6XWciHnK2xidcvSfyzjXNW15oVw6Uxqsi/vdHG2J3uM4n7i/NEqstt1PUB3DlWXdXuCXEwhnQGtA=
